### ISSUE TITLE
looking for more

### ISSUE THREAD

**Issue by toddgeist** [bleedingwolf/Ratpack#13]
hello,

I need to build some simple web services that have to run on the JVM.   I really like groovy and am picking it up fast, but I have almost no experience deploying java server stuff other than a a little Grails.  I can use Grails, but its seems like overkill.

This project seems like a good place for me to start.  It seems as though it might be possible for a guy like me to write simple services that run on the JVM.  Am I in the right place?

If so is there some document somewhere on how to build a deliverable war file or executable of some sort?  I need to deliver my code to many servers.  Tomcat will always be installed, but Jetty could work as well.  A simple hello world that goes all the way to building would be great.

Thanks very much

**Comment by trashhalo** [comment]
I am interpreting your issue as "Ability to make a WAR of a ratpack script" and if thats the case you may want to look at issue #9

**Comment by toddgeist** [comment]
ah... thank you!
