### ISSUE TITLE
Delegates broken

### ISSUE THREAD

**Issue by raymyers** [bleedingwolf/Ratpack#3]
It looks like the change to urlparams broke delegates.

For instance, the following throws "groovy.lang.MissingMethodException: No signature of method: hello.render() is applicable"

hello.groovy:

import com.bleedingwolf.ratpack.Ratpack
    import com.bleedingwolf.ratpack.RatpackServlet

```
def app = Ratpack.app {

    get("/") {
        render("index.html")
    }
}

RatpackServlet.serve(app)
```

**Comment by justinvoss** [comment]
The delegate wasn't broken, it's just that `render` required the second parameter. However, as of commit fca556e311fb64e2fea1, it's optional.
