### ISSUE TITLE
imports

### ISSUE THREAD

**Issue by mwotton** [bleedingwolf/Ratpack#8]
using the new app syntax, it doesn't seem possible to add extra imports to a ratpack app. Have I missed something?

**Comment by justinvoss** [comment]
No, you haven't missed anything. The new syntax is entirely optional; you can still write apps the original way, which will allow you to add imports. The new syntax is just to make the simple case as streamlined as possible.

**Comment by mwotton** [comment]
ah, fair enough. thanks.
